Algoritmo "IMC"

Var
   imc,peso,altura:real


Inicio
   escreva("QUAL SEU PESO?")
   leia(peso)
   escreva("QUAL A SUA ALTURA?")
   leia(altura)
   imc <-peso/(altura^2)
   se imc < 17 entao
      escreva("Imc de ",imc,",Muito abaixo do peso")
   senao
        se (imc >=17) e (imc <= 18.5) entao
           escreva("Imc de ",imc,",Abaixo do peso. ")
        senao
            se
   
   
   
   
   
   fimse
Fimalgoritmo